---
train:
  params:
    batch_size: 72
    epoch: 50 
    lr: 0.0005
    decay: 0.5
    decay_step: 10
    loss: Pinball
  save:
    save_path: "/home/tchuang/research/XGAZE/savemodel/"
    model_name: xgaze_224
    step: 4
  data:
    image: "/home/tchuang/research/XGAZE/xgaze_train/face_eye"
    label: "/home/tchuang/research/XGAZE/xgaze_train/Labels/Labels_faceeye"
  pretrains: "None"

valid:
   load:
      begin_step: 4
      end_step: 20
      steps: 4
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Gaze360-eth"
      model_name: Gaze360
   data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Image/train"
      label: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Label/test_temp.label"

test:
   load:
      begin_step: 20
      end_step: 20
      steps: 4
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Gaze360-eth"
      model_name: Gaze360
   data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Image/test"
      label: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Label/test.label"
cross:
  save_name: cross-mpii-new
  load:
      begin_step: 16
      end_step: 16
      steps: 4
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Gaze360-eth"
      load_name: False
      model_name: Gaze360
  data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Image"
      label: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Label"

# image: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/Image"
# label: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/ClusterLabel"

reader: reader_eth
device: 2
