---
train:

    params:
        batch_size: 56
        epoch: 9
        lr: 0.0005
        decay: 0.1
        decay_step: 7
        warmup: 3

    save:
      save_path: "/home/tchuang/research/RTGENE/savemodel/"
      model_name: RTGENE
      step: 10
    data:
      image: "/home/tchuang/research/RTGENE/Dataset/"
      label: "/home/tchuang/research/RTGENE/FaceBased/Label/"
      header: True
      name: RTGENE
      isFolder: True
        
    pretrain:
        enable: True
        path: "/userhome/share_hosts/work/Transformer/ComTrans/exp/Transformer-6layers/eth/checkpoint/Iter_50_trans6.pt"
        device: 0

    device: 0

reader: reader_RTGENE

# dropout = 0
# dim_feed = 512